name: 🚀 Anda RP - Deploy & Register

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🛠️ Instalar dependencias
        run: npm install

      - name: 🛰️ Registrar Comandos Slash
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_JSON }}
        run: node deploy-commands.js

      - name: ✅ Finalización
        run: echo "¡Comandos registrados correctamente!"